version: '3'
services:
#  backend:
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: product-management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
