server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /product-management-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-management
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

scheduler:
  order-clearing-job-cron: ${@hourly}