server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /product-management-service

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product-management
    username: user
    password: user
  flyway:
    url: jdbc:postgresql://localhost:5432/product-management
    locations: classpath:db/migration